### ISSUE TITLE
Pre-Release Required Bug Fixes

### ISSUE THREAD

**Issue by wolfbyte** [TeamofProgrammers/Bridge#2]
### Basic Actions ###
- [x] Handle Discord User Joining Server
- [x] Handle Discord User Leaving Server
- [x] Handle Image links coming from Discord. 
### Input Validation ###
- [x] Strip IRC Control chars prior to discord
- [x] Parse Discord Highlights. Replace highlight in IRC with 
- [x] Parse discord messages like bold/underline.
- [x] Handle Discord Actions

### Basic Error Handling: ###
- [x] Attempt to Reconnect to IRC server on connection lost. 
- [x] Decide how to handle a user being kicked from IRC, but still on discord.

**Comment by wolfbyte** [comment]
Added discord to irc highlight.
Added IRC to discord highlight.

**Comment by CloudyOne** [comment]
Added handling of actions bi-directionally.
Added conversion of formatting for bold. underline, italics, strikethrough (only supported on select irc clients) bi-directionally between discord and irc

**Comment by CloudyOne** [comment]
Added handling of user leaving discord server
Added handling of user joining discord server
Added handling of attachments to discord messages being relayed to IRC

**Comment by CloudyOne** [comment]
Also on the handling of user being kicked from IRC but still on discord... that's something we should ignore for now. 

Longterm we can handle it, assuming bot has roles, by creating an Exclusion role specific to that channel that hides it from the user. Then anytime a user joins a channel on IRC we'll have to check to see if he has that role in discord and remove it.

**Comment by CloudyOne** [comment]
Added handling of Irc server disconnect. Server should now attempt to reconnect

**Comment by CloudyOne** [comment]
Changing of roles now will correctly join and part people from channels
